
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `GamePlayer` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/wasm-compiler-edge"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model GamePlayer
 * 
 */
export type GamePlayerModel = runtime.Types.Result.DefaultSelection<Prisma.$GamePlayerPayload>

export type AggregateGamePlayer = {
  _count: GamePlayerCountAggregateOutputType | null
  _avg: GamePlayerAvgAggregateOutputType | null
  _sum: GamePlayerSumAggregateOutputType | null
  _min: GamePlayerMinAggregateOutputType | null
  _max: GamePlayerMaxAggregateOutputType | null
}

export type GamePlayerAvgAggregateOutputType = {
  seat: number | null
  finalScore: number | null
}

export type GamePlayerSumAggregateOutputType = {
  seat: number | null
  finalScore: number | null
}

export type GamePlayerMinAggregateOutputType = {
  id: string | null
  gameId: string | null
  userId: string | null
  guestName: string | null
  seat: number | null
  finalScore: number | null
  isActive: boolean | null
}

export type GamePlayerMaxAggregateOutputType = {
  id: string | null
  gameId: string | null
  userId: string | null
  guestName: string | null
  seat: number | null
  finalScore: number | null
  isActive: boolean | null
}

export type GamePlayerCountAggregateOutputType = {
  id: number
  gameId: number
  userId: number
  guestName: number
  seat: number
  finalScore: number
  isActive: number
  _all: number
}


export type GamePlayerAvgAggregateInputType = {
  seat?: true
  finalScore?: true
}

export type GamePlayerSumAggregateInputType = {
  seat?: true
  finalScore?: true
}

export type GamePlayerMinAggregateInputType = {
  id?: true
  gameId?: true
  userId?: true
  guestName?: true
  seat?: true
  finalScore?: true
  isActive?: true
}

export type GamePlayerMaxAggregateInputType = {
  id?: true
  gameId?: true
  userId?: true
  guestName?: true
  seat?: true
  finalScore?: true
  isActive?: true
}

export type GamePlayerCountAggregateInputType = {
  id?: true
  gameId?: true
  userId?: true
  guestName?: true
  seat?: true
  finalScore?: true
  isActive?: true
  _all?: true
}

export type GamePlayerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GamePlayer to aggregate.
   */
  where?: Prisma.GamePlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GamePlayers to fetch.
   */
  orderBy?: Prisma.GamePlayerOrderByWithRelationInput | Prisma.GamePlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GamePlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GamePlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GamePlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned GamePlayers
  **/
  _count?: true | GamePlayerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GamePlayerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GamePlayerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GamePlayerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GamePlayerMaxAggregateInputType
}

export type GetGamePlayerAggregateType<T extends GamePlayerAggregateArgs> = {
      [P in keyof T & keyof AggregateGamePlayer]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGamePlayer[P]>
    : Prisma.GetScalarType<T[P], AggregateGamePlayer[P]>
}




export type GamePlayerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GamePlayerWhereInput
  orderBy?: Prisma.GamePlayerOrderByWithAggregationInput | Prisma.GamePlayerOrderByWithAggregationInput[]
  by: Prisma.GamePlayerScalarFieldEnum[] | Prisma.GamePlayerScalarFieldEnum
  having?: Prisma.GamePlayerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GamePlayerCountAggregateInputType | true
  _avg?: GamePlayerAvgAggregateInputType
  _sum?: GamePlayerSumAggregateInputType
  _min?: GamePlayerMinAggregateInputType
  _max?: GamePlayerMaxAggregateInputType
}

export type GamePlayerGroupByOutputType = {
  id: string
  gameId: string
  userId: string | null
  guestName: string | null
  seat: number
  finalScore: number
  isActive: boolean
  _count: GamePlayerCountAggregateOutputType | null
  _avg: GamePlayerAvgAggregateOutputType | null
  _sum: GamePlayerSumAggregateOutputType | null
  _min: GamePlayerMinAggregateOutputType | null
  _max: GamePlayerMaxAggregateOutputType | null
}

export type GetGamePlayerGroupByPayload<T extends GamePlayerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GamePlayerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GamePlayerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GamePlayerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GamePlayerGroupByOutputType[P]>
      }
    >
  >



export type GamePlayerWhereInput = {
  AND?: Prisma.GamePlayerWhereInput | Prisma.GamePlayerWhereInput[]
  OR?: Prisma.GamePlayerWhereInput[]
  NOT?: Prisma.GamePlayerWhereInput | Prisma.GamePlayerWhereInput[]
  id?: Prisma.StringFilter<"GamePlayer"> | string
  gameId?: Prisma.StringFilter<"GamePlayer"> | string
  userId?: Prisma.StringNullableFilter<"GamePlayer"> | string | null
  guestName?: Prisma.StringNullableFilter<"GamePlayer"> | string | null
  seat?: Prisma.IntFilter<"GamePlayer"> | number
  finalScore?: Prisma.IntFilter<"GamePlayer"> | number
  isActive?: Prisma.BoolFilter<"GamePlayer"> | boolean
  game?: Prisma.XOR<Prisma.GameScalarRelationFilter, Prisma.GameWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}

export type GamePlayerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  guestName?: Prisma.SortOrderInput | Prisma.SortOrder
  seat?: Prisma.SortOrder
  finalScore?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  game?: Prisma.GameOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type GamePlayerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  gameId_seat?: Prisma.GamePlayerGameIdSeatCompoundUniqueInput
  AND?: Prisma.GamePlayerWhereInput | Prisma.GamePlayerWhereInput[]
  OR?: Prisma.GamePlayerWhereInput[]
  NOT?: Prisma.GamePlayerWhereInput | Prisma.GamePlayerWhereInput[]
  gameId?: Prisma.StringFilter<"GamePlayer"> | string
  userId?: Prisma.StringNullableFilter<"GamePlayer"> | string | null
  guestName?: Prisma.StringNullableFilter<"GamePlayer"> | string | null
  seat?: Prisma.IntFilter<"GamePlayer"> | number
  finalScore?: Prisma.IntFilter<"GamePlayer"> | number
  isActive?: Prisma.BoolFilter<"GamePlayer"> | boolean
  game?: Prisma.XOR<Prisma.GameScalarRelationFilter, Prisma.GameWhereInput>
  user?: Prisma.XOR<Prisma.UserNullableScalarRelationFilter, Prisma.UserWhereInput> | null
}, "id" | "gameId_seat">

export type GamePlayerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  userId?: Prisma.SortOrderInput | Prisma.SortOrder
  guestName?: Prisma.SortOrderInput | Prisma.SortOrder
  seat?: Prisma.SortOrder
  finalScore?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  _count?: Prisma.GamePlayerCountOrderByAggregateInput
  _avg?: Prisma.GamePlayerAvgOrderByAggregateInput
  _max?: Prisma.GamePlayerMaxOrderByAggregateInput
  _min?: Prisma.GamePlayerMinOrderByAggregateInput
  _sum?: Prisma.GamePlayerSumOrderByAggregateInput
}

export type GamePlayerScalarWhereWithAggregatesInput = {
  AND?: Prisma.GamePlayerScalarWhereWithAggregatesInput | Prisma.GamePlayerScalarWhereWithAggregatesInput[]
  OR?: Prisma.GamePlayerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GamePlayerScalarWhereWithAggregatesInput | Prisma.GamePlayerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"GamePlayer"> | string
  gameId?: Prisma.StringWithAggregatesFilter<"GamePlayer"> | string
  userId?: Prisma.StringNullableWithAggregatesFilter<"GamePlayer"> | string | null
  guestName?: Prisma.StringNullableWithAggregatesFilter<"GamePlayer"> | string | null
  seat?: Prisma.IntWithAggregatesFilter<"GamePlayer"> | number
  finalScore?: Prisma.IntWithAggregatesFilter<"GamePlayer"> | number
  isActive?: Prisma.BoolWithAggregatesFilter<"GamePlayer"> | boolean
}

export type GamePlayerCreateInput = {
  id?: string
  guestName?: string | null
  seat: number
  finalScore?: number
  isActive?: boolean
  game: Prisma.GameCreateNestedOneWithoutPlayersInput
  user?: Prisma.UserCreateNestedOneWithoutGamePlayersInput
}

export type GamePlayerUncheckedCreateInput = {
  id?: string
  gameId: string
  userId?: string | null
  guestName?: string | null
  seat: number
  finalScore?: number
  isActive?: boolean
}

export type GamePlayerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  finalScore?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  game?: Prisma.GameUpdateOneRequiredWithoutPlayersNestedInput
  user?: Prisma.UserUpdateOneWithoutGamePlayersNestedInput
}

export type GamePlayerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  finalScore?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type GamePlayerCreateManyInput = {
  id?: string
  gameId: string
  userId?: string | null
  guestName?: string | null
  seat: number
  finalScore?: number
  isActive?: boolean
}

export type GamePlayerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  finalScore?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type GamePlayerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  finalScore?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type GamePlayerListRelationFilter = {
  every?: Prisma.GamePlayerWhereInput
  some?: Prisma.GamePlayerWhereInput
  none?: Prisma.GamePlayerWhereInput
}

export type GamePlayerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type GamePlayerGameIdSeatCompoundUniqueInput = {
  gameId: string
  seat: number
}

export type GamePlayerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  guestName?: Prisma.SortOrder
  seat?: Prisma.SortOrder
  finalScore?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
}

export type GamePlayerAvgOrderByAggregateInput = {
  seat?: Prisma.SortOrder
  finalScore?: Prisma.SortOrder
}

export type GamePlayerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  guestName?: Prisma.SortOrder
  seat?: Prisma.SortOrder
  finalScore?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
}

export type GamePlayerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  guestName?: Prisma.SortOrder
  seat?: Prisma.SortOrder
  finalScore?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
}

export type GamePlayerSumOrderByAggregateInput = {
  seat?: Prisma.SortOrder
  finalScore?: Prisma.SortOrder
}

export type GamePlayerCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.GamePlayerCreateWithoutUserInput, Prisma.GamePlayerUncheckedCreateWithoutUserInput> | Prisma.GamePlayerCreateWithoutUserInput[] | Prisma.GamePlayerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GamePlayerCreateOrConnectWithoutUserInput | Prisma.GamePlayerCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.GamePlayerCreateManyUserInputEnvelope
  connect?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
}

export type GamePlayerUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.GamePlayerCreateWithoutUserInput, Prisma.GamePlayerUncheckedCreateWithoutUserInput> | Prisma.GamePlayerCreateWithoutUserInput[] | Prisma.GamePlayerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GamePlayerCreateOrConnectWithoutUserInput | Prisma.GamePlayerCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.GamePlayerCreateManyUserInputEnvelope
  connect?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
}

export type GamePlayerUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.GamePlayerCreateWithoutUserInput, Prisma.GamePlayerUncheckedCreateWithoutUserInput> | Prisma.GamePlayerCreateWithoutUserInput[] | Prisma.GamePlayerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GamePlayerCreateOrConnectWithoutUserInput | Prisma.GamePlayerCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.GamePlayerUpsertWithWhereUniqueWithoutUserInput | Prisma.GamePlayerUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.GamePlayerCreateManyUserInputEnvelope
  set?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  disconnect?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  delete?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  connect?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  update?: Prisma.GamePlayerUpdateWithWhereUniqueWithoutUserInput | Prisma.GamePlayerUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.GamePlayerUpdateManyWithWhereWithoutUserInput | Prisma.GamePlayerUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.GamePlayerScalarWhereInput | Prisma.GamePlayerScalarWhereInput[]
}

export type GamePlayerUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.GamePlayerCreateWithoutUserInput, Prisma.GamePlayerUncheckedCreateWithoutUserInput> | Prisma.GamePlayerCreateWithoutUserInput[] | Prisma.GamePlayerUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.GamePlayerCreateOrConnectWithoutUserInput | Prisma.GamePlayerCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.GamePlayerUpsertWithWhereUniqueWithoutUserInput | Prisma.GamePlayerUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.GamePlayerCreateManyUserInputEnvelope
  set?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  disconnect?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  delete?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  connect?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  update?: Prisma.GamePlayerUpdateWithWhereUniqueWithoutUserInput | Prisma.GamePlayerUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.GamePlayerUpdateManyWithWhereWithoutUserInput | Prisma.GamePlayerUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.GamePlayerScalarWhereInput | Prisma.GamePlayerScalarWhereInput[]
}

export type GamePlayerCreateNestedManyWithoutGameInput = {
  create?: Prisma.XOR<Prisma.GamePlayerCreateWithoutGameInput, Prisma.GamePlayerUncheckedCreateWithoutGameInput> | Prisma.GamePlayerCreateWithoutGameInput[] | Prisma.GamePlayerUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.GamePlayerCreateOrConnectWithoutGameInput | Prisma.GamePlayerCreateOrConnectWithoutGameInput[]
  createMany?: Prisma.GamePlayerCreateManyGameInputEnvelope
  connect?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
}

export type GamePlayerUncheckedCreateNestedManyWithoutGameInput = {
  create?: Prisma.XOR<Prisma.GamePlayerCreateWithoutGameInput, Prisma.GamePlayerUncheckedCreateWithoutGameInput> | Prisma.GamePlayerCreateWithoutGameInput[] | Prisma.GamePlayerUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.GamePlayerCreateOrConnectWithoutGameInput | Prisma.GamePlayerCreateOrConnectWithoutGameInput[]
  createMany?: Prisma.GamePlayerCreateManyGameInputEnvelope
  connect?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
}

export type GamePlayerUpdateManyWithoutGameNestedInput = {
  create?: Prisma.XOR<Prisma.GamePlayerCreateWithoutGameInput, Prisma.GamePlayerUncheckedCreateWithoutGameInput> | Prisma.GamePlayerCreateWithoutGameInput[] | Prisma.GamePlayerUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.GamePlayerCreateOrConnectWithoutGameInput | Prisma.GamePlayerCreateOrConnectWithoutGameInput[]
  upsert?: Prisma.GamePlayerUpsertWithWhereUniqueWithoutGameInput | Prisma.GamePlayerUpsertWithWhereUniqueWithoutGameInput[]
  createMany?: Prisma.GamePlayerCreateManyGameInputEnvelope
  set?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  disconnect?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  delete?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  connect?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  update?: Prisma.GamePlayerUpdateWithWhereUniqueWithoutGameInput | Prisma.GamePlayerUpdateWithWhereUniqueWithoutGameInput[]
  updateMany?: Prisma.GamePlayerUpdateManyWithWhereWithoutGameInput | Prisma.GamePlayerUpdateManyWithWhereWithoutGameInput[]
  deleteMany?: Prisma.GamePlayerScalarWhereInput | Prisma.GamePlayerScalarWhereInput[]
}

export type GamePlayerUncheckedUpdateManyWithoutGameNestedInput = {
  create?: Prisma.XOR<Prisma.GamePlayerCreateWithoutGameInput, Prisma.GamePlayerUncheckedCreateWithoutGameInput> | Prisma.GamePlayerCreateWithoutGameInput[] | Prisma.GamePlayerUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.GamePlayerCreateOrConnectWithoutGameInput | Prisma.GamePlayerCreateOrConnectWithoutGameInput[]
  upsert?: Prisma.GamePlayerUpsertWithWhereUniqueWithoutGameInput | Prisma.GamePlayerUpsertWithWhereUniqueWithoutGameInput[]
  createMany?: Prisma.GamePlayerCreateManyGameInputEnvelope
  set?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  disconnect?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  delete?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  connect?: Prisma.GamePlayerWhereUniqueInput | Prisma.GamePlayerWhereUniqueInput[]
  update?: Prisma.GamePlayerUpdateWithWhereUniqueWithoutGameInput | Prisma.GamePlayerUpdateWithWhereUniqueWithoutGameInput[]
  updateMany?: Prisma.GamePlayerUpdateManyWithWhereWithoutGameInput | Prisma.GamePlayerUpdateManyWithWhereWithoutGameInput[]
  deleteMany?: Prisma.GamePlayerScalarWhereInput | Prisma.GamePlayerScalarWhereInput[]
}

export type GamePlayerCreateWithoutUserInput = {
  id?: string
  guestName?: string | null
  seat: number
  finalScore?: number
  isActive?: boolean
  game: Prisma.GameCreateNestedOneWithoutPlayersInput
}

export type GamePlayerUncheckedCreateWithoutUserInput = {
  id?: string
  gameId: string
  guestName?: string | null
  seat: number
  finalScore?: number
  isActive?: boolean
}

export type GamePlayerCreateOrConnectWithoutUserInput = {
  where: Prisma.GamePlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.GamePlayerCreateWithoutUserInput, Prisma.GamePlayerUncheckedCreateWithoutUserInput>
}

export type GamePlayerCreateManyUserInputEnvelope = {
  data: Prisma.GamePlayerCreateManyUserInput | Prisma.GamePlayerCreateManyUserInput[]
}

export type GamePlayerUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.GamePlayerWhereUniqueInput
  update: Prisma.XOR<Prisma.GamePlayerUpdateWithoutUserInput, Prisma.GamePlayerUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.GamePlayerCreateWithoutUserInput, Prisma.GamePlayerUncheckedCreateWithoutUserInput>
}

export type GamePlayerUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.GamePlayerWhereUniqueInput
  data: Prisma.XOR<Prisma.GamePlayerUpdateWithoutUserInput, Prisma.GamePlayerUncheckedUpdateWithoutUserInput>
}

export type GamePlayerUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.GamePlayerScalarWhereInput
  data: Prisma.XOR<Prisma.GamePlayerUpdateManyMutationInput, Prisma.GamePlayerUncheckedUpdateManyWithoutUserInput>
}

export type GamePlayerScalarWhereInput = {
  AND?: Prisma.GamePlayerScalarWhereInput | Prisma.GamePlayerScalarWhereInput[]
  OR?: Prisma.GamePlayerScalarWhereInput[]
  NOT?: Prisma.GamePlayerScalarWhereInput | Prisma.GamePlayerScalarWhereInput[]
  id?: Prisma.StringFilter<"GamePlayer"> | string
  gameId?: Prisma.StringFilter<"GamePlayer"> | string
  userId?: Prisma.StringNullableFilter<"GamePlayer"> | string | null
  guestName?: Prisma.StringNullableFilter<"GamePlayer"> | string | null
  seat?: Prisma.IntFilter<"GamePlayer"> | number
  finalScore?: Prisma.IntFilter<"GamePlayer"> | number
  isActive?: Prisma.BoolFilter<"GamePlayer"> | boolean
}

export type GamePlayerCreateWithoutGameInput = {
  id?: string
  guestName?: string | null
  seat: number
  finalScore?: number
  isActive?: boolean
  user?: Prisma.UserCreateNestedOneWithoutGamePlayersInput
}

export type GamePlayerUncheckedCreateWithoutGameInput = {
  id?: string
  userId?: string | null
  guestName?: string | null
  seat: number
  finalScore?: number
  isActive?: boolean
}

export type GamePlayerCreateOrConnectWithoutGameInput = {
  where: Prisma.GamePlayerWhereUniqueInput
  create: Prisma.XOR<Prisma.GamePlayerCreateWithoutGameInput, Prisma.GamePlayerUncheckedCreateWithoutGameInput>
}

export type GamePlayerCreateManyGameInputEnvelope = {
  data: Prisma.GamePlayerCreateManyGameInput | Prisma.GamePlayerCreateManyGameInput[]
}

export type GamePlayerUpsertWithWhereUniqueWithoutGameInput = {
  where: Prisma.GamePlayerWhereUniqueInput
  update: Prisma.XOR<Prisma.GamePlayerUpdateWithoutGameInput, Prisma.GamePlayerUncheckedUpdateWithoutGameInput>
  create: Prisma.XOR<Prisma.GamePlayerCreateWithoutGameInput, Prisma.GamePlayerUncheckedCreateWithoutGameInput>
}

export type GamePlayerUpdateWithWhereUniqueWithoutGameInput = {
  where: Prisma.GamePlayerWhereUniqueInput
  data: Prisma.XOR<Prisma.GamePlayerUpdateWithoutGameInput, Prisma.GamePlayerUncheckedUpdateWithoutGameInput>
}

export type GamePlayerUpdateManyWithWhereWithoutGameInput = {
  where: Prisma.GamePlayerScalarWhereInput
  data: Prisma.XOR<Prisma.GamePlayerUpdateManyMutationInput, Prisma.GamePlayerUncheckedUpdateManyWithoutGameInput>
}

export type GamePlayerCreateManyUserInput = {
  id?: string
  gameId: string
  guestName?: string | null
  seat: number
  finalScore?: number
  isActive?: boolean
}

export type GamePlayerUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  finalScore?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  game?: Prisma.GameUpdateOneRequiredWithoutPlayersNestedInput
}

export type GamePlayerUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameId?: Prisma.StringFieldUpdateOperationsInput | string
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  finalScore?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type GamePlayerUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameId?: Prisma.StringFieldUpdateOperationsInput | string
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  finalScore?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type GamePlayerCreateManyGameInput = {
  id?: string
  userId?: string | null
  guestName?: string | null
  seat: number
  finalScore?: number
  isActive?: boolean
}

export type GamePlayerUpdateWithoutGameInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  finalScore?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  user?: Prisma.UserUpdateOneWithoutGamePlayersNestedInput
}

export type GamePlayerUncheckedUpdateWithoutGameInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  finalScore?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}

export type GamePlayerUncheckedUpdateManyWithoutGameInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  guestName?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  finalScore?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type GamePlayerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gameId?: boolean
  userId?: boolean
  guestName?: boolean
  seat?: boolean
  finalScore?: boolean
  isActive?: boolean
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
  user?: boolean | Prisma.GamePlayer$userArgs<ExtArgs>
}, ExtArgs["result"]["gamePlayer"]>

export type GamePlayerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gameId?: boolean
  userId?: boolean
  guestName?: boolean
  seat?: boolean
  finalScore?: boolean
  isActive?: boolean
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
  user?: boolean | Prisma.GamePlayer$userArgs<ExtArgs>
}, ExtArgs["result"]["gamePlayer"]>

export type GamePlayerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gameId?: boolean
  userId?: boolean
  guestName?: boolean
  seat?: boolean
  finalScore?: boolean
  isActive?: boolean
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
  user?: boolean | Prisma.GamePlayer$userArgs<ExtArgs>
}, ExtArgs["result"]["gamePlayer"]>

export type GamePlayerSelectScalar = {
  id?: boolean
  gameId?: boolean
  userId?: boolean
  guestName?: boolean
  seat?: boolean
  finalScore?: boolean
  isActive?: boolean
}

export type GamePlayerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "gameId" | "userId" | "guestName" | "seat" | "finalScore" | "isActive", ExtArgs["result"]["gamePlayer"]>
export type GamePlayerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
  user?: boolean | Prisma.GamePlayer$userArgs<ExtArgs>
}
export type GamePlayerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
  user?: boolean | Prisma.GamePlayer$userArgs<ExtArgs>
}
export type GamePlayerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
  user?: boolean | Prisma.GamePlayer$userArgs<ExtArgs>
}

export type $GamePlayerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "GamePlayer"
  objects: {
    game: Prisma.$GamePayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs> | null
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    gameId: string
    userId: string | null
    guestName: string | null
    seat: number
    finalScore: number
    isActive: boolean
  }, ExtArgs["result"]["gamePlayer"]>
  composites: {}
}

export type GamePlayerGetPayload<S extends boolean | null | undefined | GamePlayerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GamePlayerPayload, S>

export type GamePlayerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GamePlayerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GamePlayerCountAggregateInputType | true
  }

export interface GamePlayerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['GamePlayer'], meta: { name: 'GamePlayer' } }
  /**
   * Find zero or one GamePlayer that matches the filter.
   * @param {GamePlayerFindUniqueArgs} args - Arguments to find a GamePlayer
   * @example
   * // Get one GamePlayer
   * const gamePlayer = await prisma.gamePlayer.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GamePlayerFindUniqueArgs>(args: Prisma.SelectSubset<T, GamePlayerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GamePlayerClient<runtime.Types.Result.GetResult<Prisma.$GamePlayerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one GamePlayer that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GamePlayerFindUniqueOrThrowArgs} args - Arguments to find a GamePlayer
   * @example
   * // Get one GamePlayer
   * const gamePlayer = await prisma.gamePlayer.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GamePlayerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GamePlayerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GamePlayerClient<runtime.Types.Result.GetResult<Prisma.$GamePlayerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GamePlayer that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GamePlayerFindFirstArgs} args - Arguments to find a GamePlayer
   * @example
   * // Get one GamePlayer
   * const gamePlayer = await prisma.gamePlayer.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GamePlayerFindFirstArgs>(args?: Prisma.SelectSubset<T, GamePlayerFindFirstArgs<ExtArgs>>): Prisma.Prisma__GamePlayerClient<runtime.Types.Result.GetResult<Prisma.$GamePlayerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first GamePlayer that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GamePlayerFindFirstOrThrowArgs} args - Arguments to find a GamePlayer
   * @example
   * // Get one GamePlayer
   * const gamePlayer = await prisma.gamePlayer.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GamePlayerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GamePlayerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GamePlayerClient<runtime.Types.Result.GetResult<Prisma.$GamePlayerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more GamePlayers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GamePlayerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all GamePlayers
   * const gamePlayers = await prisma.gamePlayer.findMany()
   * 
   * // Get first 10 GamePlayers
   * const gamePlayers = await prisma.gamePlayer.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const gamePlayerWithIdOnly = await prisma.gamePlayer.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GamePlayerFindManyArgs>(args?: Prisma.SelectSubset<T, GamePlayerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GamePlayerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a GamePlayer.
   * @param {GamePlayerCreateArgs} args - Arguments to create a GamePlayer.
   * @example
   * // Create one GamePlayer
   * const GamePlayer = await prisma.gamePlayer.create({
   *   data: {
   *     // ... data to create a GamePlayer
   *   }
   * })
   * 
   */
  create<T extends GamePlayerCreateArgs>(args: Prisma.SelectSubset<T, GamePlayerCreateArgs<ExtArgs>>): Prisma.Prisma__GamePlayerClient<runtime.Types.Result.GetResult<Prisma.$GamePlayerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many GamePlayers.
   * @param {GamePlayerCreateManyArgs} args - Arguments to create many GamePlayers.
   * @example
   * // Create many GamePlayers
   * const gamePlayer = await prisma.gamePlayer.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GamePlayerCreateManyArgs>(args?: Prisma.SelectSubset<T, GamePlayerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many GamePlayers and returns the data saved in the database.
   * @param {GamePlayerCreateManyAndReturnArgs} args - Arguments to create many GamePlayers.
   * @example
   * // Create many GamePlayers
   * const gamePlayer = await prisma.gamePlayer.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many GamePlayers and only return the `id`
   * const gamePlayerWithIdOnly = await prisma.gamePlayer.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GamePlayerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GamePlayerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GamePlayerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a GamePlayer.
   * @param {GamePlayerDeleteArgs} args - Arguments to delete one GamePlayer.
   * @example
   * // Delete one GamePlayer
   * const GamePlayer = await prisma.gamePlayer.delete({
   *   where: {
   *     // ... filter to delete one GamePlayer
   *   }
   * })
   * 
   */
  delete<T extends GamePlayerDeleteArgs>(args: Prisma.SelectSubset<T, GamePlayerDeleteArgs<ExtArgs>>): Prisma.Prisma__GamePlayerClient<runtime.Types.Result.GetResult<Prisma.$GamePlayerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one GamePlayer.
   * @param {GamePlayerUpdateArgs} args - Arguments to update one GamePlayer.
   * @example
   * // Update one GamePlayer
   * const gamePlayer = await prisma.gamePlayer.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GamePlayerUpdateArgs>(args: Prisma.SelectSubset<T, GamePlayerUpdateArgs<ExtArgs>>): Prisma.Prisma__GamePlayerClient<runtime.Types.Result.GetResult<Prisma.$GamePlayerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more GamePlayers.
   * @param {GamePlayerDeleteManyArgs} args - Arguments to filter GamePlayers to delete.
   * @example
   * // Delete a few GamePlayers
   * const { count } = await prisma.gamePlayer.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GamePlayerDeleteManyArgs>(args?: Prisma.SelectSubset<T, GamePlayerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GamePlayers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GamePlayerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many GamePlayers
   * const gamePlayer = await prisma.gamePlayer.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GamePlayerUpdateManyArgs>(args: Prisma.SelectSubset<T, GamePlayerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more GamePlayers and returns the data updated in the database.
   * @param {GamePlayerUpdateManyAndReturnArgs} args - Arguments to update many GamePlayers.
   * @example
   * // Update many GamePlayers
   * const gamePlayer = await prisma.gamePlayer.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more GamePlayers and only return the `id`
   * const gamePlayerWithIdOnly = await prisma.gamePlayer.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GamePlayerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GamePlayerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GamePlayerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one GamePlayer.
   * @param {GamePlayerUpsertArgs} args - Arguments to update or create a GamePlayer.
   * @example
   * // Update or create a GamePlayer
   * const gamePlayer = await prisma.gamePlayer.upsert({
   *   create: {
   *     // ... data to create a GamePlayer
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the GamePlayer we want to update
   *   }
   * })
   */
  upsert<T extends GamePlayerUpsertArgs>(args: Prisma.SelectSubset<T, GamePlayerUpsertArgs<ExtArgs>>): Prisma.Prisma__GamePlayerClient<runtime.Types.Result.GetResult<Prisma.$GamePlayerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of GamePlayers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GamePlayerCountArgs} args - Arguments to filter GamePlayers to count.
   * @example
   * // Count the number of GamePlayers
   * const count = await prisma.gamePlayer.count({
   *   where: {
   *     // ... the filter for the GamePlayers we want to count
   *   }
   * })
  **/
  count<T extends GamePlayerCountArgs>(
    args?: Prisma.Subset<T, GamePlayerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GamePlayerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a GamePlayer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GamePlayerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GamePlayerAggregateArgs>(args: Prisma.Subset<T, GamePlayerAggregateArgs>): Prisma.PrismaPromise<GetGamePlayerAggregateType<T>>

  /**
   * Group by GamePlayer.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GamePlayerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GamePlayerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GamePlayerGroupByArgs['orderBy'] }
      : { orderBy?: GamePlayerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GamePlayerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGamePlayerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the GamePlayer model
 */
readonly fields: GamePlayerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for GamePlayer.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GamePlayerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  game<T extends Prisma.GameDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GameDefaultArgs<ExtArgs>>): Prisma.Prisma__GameClient<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.GamePlayer$userArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GamePlayer$userArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the GamePlayer model
 */
export interface GamePlayerFieldRefs {
  readonly id: Prisma.FieldRef<"GamePlayer", 'String'>
  readonly gameId: Prisma.FieldRef<"GamePlayer", 'String'>
  readonly userId: Prisma.FieldRef<"GamePlayer", 'String'>
  readonly guestName: Prisma.FieldRef<"GamePlayer", 'String'>
  readonly seat: Prisma.FieldRef<"GamePlayer", 'Int'>
  readonly finalScore: Prisma.FieldRef<"GamePlayer", 'Int'>
  readonly isActive: Prisma.FieldRef<"GamePlayer", 'Boolean'>
}
    

// Custom InputTypes
/**
 * GamePlayer findUnique
 */
export type GamePlayerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GamePlayer
   */
  select?: Prisma.GamePlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GamePlayer
   */
  omit?: Prisma.GamePlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GamePlayerInclude<ExtArgs> | null
  /**
   * Filter, which GamePlayer to fetch.
   */
  where: Prisma.GamePlayerWhereUniqueInput
}

/**
 * GamePlayer findUniqueOrThrow
 */
export type GamePlayerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GamePlayer
   */
  select?: Prisma.GamePlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GamePlayer
   */
  omit?: Prisma.GamePlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GamePlayerInclude<ExtArgs> | null
  /**
   * Filter, which GamePlayer to fetch.
   */
  where: Prisma.GamePlayerWhereUniqueInput
}

/**
 * GamePlayer findFirst
 */
export type GamePlayerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GamePlayer
   */
  select?: Prisma.GamePlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GamePlayer
   */
  omit?: Prisma.GamePlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GamePlayerInclude<ExtArgs> | null
  /**
   * Filter, which GamePlayer to fetch.
   */
  where?: Prisma.GamePlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GamePlayers to fetch.
   */
  orderBy?: Prisma.GamePlayerOrderByWithRelationInput | Prisma.GamePlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GamePlayers.
   */
  cursor?: Prisma.GamePlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GamePlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GamePlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GamePlayers.
   */
  distinct?: Prisma.GamePlayerScalarFieldEnum | Prisma.GamePlayerScalarFieldEnum[]
}

/**
 * GamePlayer findFirstOrThrow
 */
export type GamePlayerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GamePlayer
   */
  select?: Prisma.GamePlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GamePlayer
   */
  omit?: Prisma.GamePlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GamePlayerInclude<ExtArgs> | null
  /**
   * Filter, which GamePlayer to fetch.
   */
  where?: Prisma.GamePlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GamePlayers to fetch.
   */
  orderBy?: Prisma.GamePlayerOrderByWithRelationInput | Prisma.GamePlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for GamePlayers.
   */
  cursor?: Prisma.GamePlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GamePlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GamePlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GamePlayers.
   */
  distinct?: Prisma.GamePlayerScalarFieldEnum | Prisma.GamePlayerScalarFieldEnum[]
}

/**
 * GamePlayer findMany
 */
export type GamePlayerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GamePlayer
   */
  select?: Prisma.GamePlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GamePlayer
   */
  omit?: Prisma.GamePlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GamePlayerInclude<ExtArgs> | null
  /**
   * Filter, which GamePlayers to fetch.
   */
  where?: Prisma.GamePlayerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of GamePlayers to fetch.
   */
  orderBy?: Prisma.GamePlayerOrderByWithRelationInput | Prisma.GamePlayerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing GamePlayers.
   */
  cursor?: Prisma.GamePlayerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` GamePlayers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` GamePlayers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of GamePlayers.
   */
  distinct?: Prisma.GamePlayerScalarFieldEnum | Prisma.GamePlayerScalarFieldEnum[]
}

/**
 * GamePlayer create
 */
export type GamePlayerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GamePlayer
   */
  select?: Prisma.GamePlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GamePlayer
   */
  omit?: Prisma.GamePlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GamePlayerInclude<ExtArgs> | null
  /**
   * The data needed to create a GamePlayer.
   */
  data: Prisma.XOR<Prisma.GamePlayerCreateInput, Prisma.GamePlayerUncheckedCreateInput>
}

/**
 * GamePlayer createMany
 */
export type GamePlayerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many GamePlayers.
   */
  data: Prisma.GamePlayerCreateManyInput | Prisma.GamePlayerCreateManyInput[]
}

/**
 * GamePlayer createManyAndReturn
 */
export type GamePlayerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GamePlayer
   */
  select?: Prisma.GamePlayerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GamePlayer
   */
  omit?: Prisma.GamePlayerOmit<ExtArgs> | null
  /**
   * The data used to create many GamePlayers.
   */
  data: Prisma.GamePlayerCreateManyInput | Prisma.GamePlayerCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GamePlayerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * GamePlayer update
 */
export type GamePlayerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GamePlayer
   */
  select?: Prisma.GamePlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GamePlayer
   */
  omit?: Prisma.GamePlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GamePlayerInclude<ExtArgs> | null
  /**
   * The data needed to update a GamePlayer.
   */
  data: Prisma.XOR<Prisma.GamePlayerUpdateInput, Prisma.GamePlayerUncheckedUpdateInput>
  /**
   * Choose, which GamePlayer to update.
   */
  where: Prisma.GamePlayerWhereUniqueInput
}

/**
 * GamePlayer updateMany
 */
export type GamePlayerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update GamePlayers.
   */
  data: Prisma.XOR<Prisma.GamePlayerUpdateManyMutationInput, Prisma.GamePlayerUncheckedUpdateManyInput>
  /**
   * Filter which GamePlayers to update
   */
  where?: Prisma.GamePlayerWhereInput
  /**
   * Limit how many GamePlayers to update.
   */
  limit?: number
}

/**
 * GamePlayer updateManyAndReturn
 */
export type GamePlayerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GamePlayer
   */
  select?: Prisma.GamePlayerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the GamePlayer
   */
  omit?: Prisma.GamePlayerOmit<ExtArgs> | null
  /**
   * The data used to update GamePlayers.
   */
  data: Prisma.XOR<Prisma.GamePlayerUpdateManyMutationInput, Prisma.GamePlayerUncheckedUpdateManyInput>
  /**
   * Filter which GamePlayers to update
   */
  where?: Prisma.GamePlayerWhereInput
  /**
   * Limit how many GamePlayers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GamePlayerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * GamePlayer upsert
 */
export type GamePlayerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GamePlayer
   */
  select?: Prisma.GamePlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GamePlayer
   */
  omit?: Prisma.GamePlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GamePlayerInclude<ExtArgs> | null
  /**
   * The filter to search for the GamePlayer to update in case it exists.
   */
  where: Prisma.GamePlayerWhereUniqueInput
  /**
   * In case the GamePlayer found by the `where` argument doesn't exist, create a new GamePlayer with this data.
   */
  create: Prisma.XOR<Prisma.GamePlayerCreateInput, Prisma.GamePlayerUncheckedCreateInput>
  /**
   * In case the GamePlayer was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GamePlayerUpdateInput, Prisma.GamePlayerUncheckedUpdateInput>
}

/**
 * GamePlayer delete
 */
export type GamePlayerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GamePlayer
   */
  select?: Prisma.GamePlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GamePlayer
   */
  omit?: Prisma.GamePlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GamePlayerInclude<ExtArgs> | null
  /**
   * Filter which GamePlayer to delete.
   */
  where: Prisma.GamePlayerWhereUniqueInput
}

/**
 * GamePlayer deleteMany
 */
export type GamePlayerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which GamePlayers to delete
   */
  where?: Prisma.GamePlayerWhereInput
  /**
   * Limit how many GamePlayers to delete.
   */
  limit?: number
}

/**
 * GamePlayer.user
 */
export type GamePlayer$userArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the User
   */
  select?: Prisma.UserSelect<ExtArgs> | null
  /**
   * Omit specific fields from the User
   */
  omit?: Prisma.UserOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.UserInclude<ExtArgs> | null
  where?: Prisma.UserWhereInput
}

/**
 * GamePlayer without action
 */
export type GamePlayerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GamePlayer
   */
  select?: Prisma.GamePlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GamePlayer
   */
  omit?: Prisma.GamePlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GamePlayerInclude<ExtArgs> | null
}
