
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Game` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/wasm-compiler-edge"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Game
 * 
 */
export type GameModel = runtime.Types.Result.DefaultSelection<Prisma.$GamePayload>

export type AggregateGame = {
  _count: GameCountAggregateOutputType | null
  _avg: GameAvgAggregateOutputType | null
  _sum: GameSumAggregateOutputType | null
  _min: GameMinAggregateOutputType | null
  _max: GameMaxAggregateOutputType | null
}

export type GameAvgAggregateOutputType = {
  maxPlayers: number | null
}

export type GameSumAggregateOutputType = {
  maxPlayers: number | null
}

export type GameMinAggregateOutputType = {
  id: string | null
  mode: string | null
  status: string | null
  maxPlayers: number | null
  settings: string | null
  createdAt: Date | null
  finishedAt: Date | null
}

export type GameMaxAggregateOutputType = {
  id: string | null
  mode: string | null
  status: string | null
  maxPlayers: number | null
  settings: string | null
  createdAt: Date | null
  finishedAt: Date | null
}

export type GameCountAggregateOutputType = {
  id: number
  mode: number
  status: number
  maxPlayers: number
  settings: number
  createdAt: number
  finishedAt: number
  _all: number
}


export type GameAvgAggregateInputType = {
  maxPlayers?: true
}

export type GameSumAggregateInputType = {
  maxPlayers?: true
}

export type GameMinAggregateInputType = {
  id?: true
  mode?: true
  status?: true
  maxPlayers?: true
  settings?: true
  createdAt?: true
  finishedAt?: true
}

export type GameMaxAggregateInputType = {
  id?: true
  mode?: true
  status?: true
  maxPlayers?: true
  settings?: true
  createdAt?: true
  finishedAt?: true
}

export type GameCountAggregateInputType = {
  id?: true
  mode?: true
  status?: true
  maxPlayers?: true
  settings?: true
  createdAt?: true
  finishedAt?: true
  _all?: true
}

export type GameAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Game to aggregate.
   */
  where?: Prisma.GameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Games to fetch.
   */
  orderBy?: Prisma.GameOrderByWithRelationInput | Prisma.GameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.GameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Games from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Games.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Games
  **/
  _count?: true | GameCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: GameAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: GameSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: GameMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: GameMaxAggregateInputType
}

export type GetGameAggregateType<T extends GameAggregateArgs> = {
      [P in keyof T & keyof AggregateGame]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateGame[P]>
    : Prisma.GetScalarType<T[P], AggregateGame[P]>
}




export type GameGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GameWhereInput
  orderBy?: Prisma.GameOrderByWithAggregationInput | Prisma.GameOrderByWithAggregationInput[]
  by: Prisma.GameScalarFieldEnum[] | Prisma.GameScalarFieldEnum
  having?: Prisma.GameScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: GameCountAggregateInputType | true
  _avg?: GameAvgAggregateInputType
  _sum?: GameSumAggregateInputType
  _min?: GameMinAggregateInputType
  _max?: GameMaxAggregateInputType
}

export type GameGroupByOutputType = {
  id: string
  mode: string
  status: string
  maxPlayers: number
  settings: string
  createdAt: Date
  finishedAt: Date | null
  _count: GameCountAggregateOutputType | null
  _avg: GameAvgAggregateOutputType | null
  _sum: GameSumAggregateOutputType | null
  _min: GameMinAggregateOutputType | null
  _max: GameMaxAggregateOutputType | null
}

export type GetGameGroupByPayload<T extends GameGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<GameGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof GameGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], GameGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], GameGroupByOutputType[P]>
      }
    >
  >



export type GameWhereInput = {
  AND?: Prisma.GameWhereInput | Prisma.GameWhereInput[]
  OR?: Prisma.GameWhereInput[]
  NOT?: Prisma.GameWhereInput | Prisma.GameWhereInput[]
  id?: Prisma.StringFilter<"Game"> | string
  mode?: Prisma.StringFilter<"Game"> | string
  status?: Prisma.StringFilter<"Game"> | string
  maxPlayers?: Prisma.IntFilter<"Game"> | number
  settings?: Prisma.StringFilter<"Game"> | string
  createdAt?: Prisma.DateTimeFilter<"Game"> | Date | string
  finishedAt?: Prisma.DateTimeNullableFilter<"Game"> | Date | string | null
  players?: Prisma.GamePlayerListRelationFilter
  moves?: Prisma.MoveListRelationFilter
  messages?: Prisma.ChatMessageListRelationFilter
}

export type GameOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  status?: Prisma.SortOrder
  maxPlayers?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  players?: Prisma.GamePlayerOrderByRelationAggregateInput
  moves?: Prisma.MoveOrderByRelationAggregateInput
  messages?: Prisma.ChatMessageOrderByRelationAggregateInput
}

export type GameWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.GameWhereInput | Prisma.GameWhereInput[]
  OR?: Prisma.GameWhereInput[]
  NOT?: Prisma.GameWhereInput | Prisma.GameWhereInput[]
  mode?: Prisma.StringFilter<"Game"> | string
  status?: Prisma.StringFilter<"Game"> | string
  maxPlayers?: Prisma.IntFilter<"Game"> | number
  settings?: Prisma.StringFilter<"Game"> | string
  createdAt?: Prisma.DateTimeFilter<"Game"> | Date | string
  finishedAt?: Prisma.DateTimeNullableFilter<"Game"> | Date | string | null
  players?: Prisma.GamePlayerListRelationFilter
  moves?: Prisma.MoveListRelationFilter
  messages?: Prisma.ChatMessageListRelationFilter
}, "id">

export type GameOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  status?: Prisma.SortOrder
  maxPlayers?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.GameCountOrderByAggregateInput
  _avg?: Prisma.GameAvgOrderByAggregateInput
  _max?: Prisma.GameMaxOrderByAggregateInput
  _min?: Prisma.GameMinOrderByAggregateInput
  _sum?: Prisma.GameSumOrderByAggregateInput
}

export type GameScalarWhereWithAggregatesInput = {
  AND?: Prisma.GameScalarWhereWithAggregatesInput | Prisma.GameScalarWhereWithAggregatesInput[]
  OR?: Prisma.GameScalarWhereWithAggregatesInput[]
  NOT?: Prisma.GameScalarWhereWithAggregatesInput | Prisma.GameScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Game"> | string
  mode?: Prisma.StringWithAggregatesFilter<"Game"> | string
  status?: Prisma.StringWithAggregatesFilter<"Game"> | string
  maxPlayers?: Prisma.IntWithAggregatesFilter<"Game"> | number
  settings?: Prisma.StringWithAggregatesFilter<"Game"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Game"> | Date | string
  finishedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Game"> | Date | string | null
}

export type GameCreateInput = {
  id: string
  mode?: string
  status?: string
  maxPlayers?: number
  settings?: string
  createdAt?: Date | string
  finishedAt?: Date | string | null
  players?: Prisma.GamePlayerCreateNestedManyWithoutGameInput
  moves?: Prisma.MoveCreateNestedManyWithoutGameInput
  messages?: Prisma.ChatMessageCreateNestedManyWithoutGameInput
}

export type GameUncheckedCreateInput = {
  id: string
  mode?: string
  status?: string
  maxPlayers?: number
  settings?: string
  createdAt?: Date | string
  finishedAt?: Date | string | null
  players?: Prisma.GamePlayerUncheckedCreateNestedManyWithoutGameInput
  moves?: Prisma.MoveUncheckedCreateNestedManyWithoutGameInput
  messages?: Prisma.ChatMessageUncheckedCreateNestedManyWithoutGameInput
}

export type GameUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  maxPlayers?: Prisma.IntFieldUpdateOperationsInput | number
  settings?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  players?: Prisma.GamePlayerUpdateManyWithoutGameNestedInput
  moves?: Prisma.MoveUpdateManyWithoutGameNestedInput
  messages?: Prisma.ChatMessageUpdateManyWithoutGameNestedInput
}

export type GameUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  maxPlayers?: Prisma.IntFieldUpdateOperationsInput | number
  settings?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  players?: Prisma.GamePlayerUncheckedUpdateManyWithoutGameNestedInput
  moves?: Prisma.MoveUncheckedUpdateManyWithoutGameNestedInput
  messages?: Prisma.ChatMessageUncheckedUpdateManyWithoutGameNestedInput
}

export type GameCreateManyInput = {
  id: string
  mode?: string
  status?: string
  maxPlayers?: number
  settings?: string
  createdAt?: Date | string
  finishedAt?: Date | string | null
}

export type GameUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  maxPlayers?: Prisma.IntFieldUpdateOperationsInput | number
  settings?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GameUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  maxPlayers?: Prisma.IntFieldUpdateOperationsInput | number
  settings?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type GameCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  status?: Prisma.SortOrder
  maxPlayers?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
}

export type GameAvgOrderByAggregateInput = {
  maxPlayers?: Prisma.SortOrder
}

export type GameMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  status?: Prisma.SortOrder
  maxPlayers?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
}

export type GameMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  mode?: Prisma.SortOrder
  status?: Prisma.SortOrder
  maxPlayers?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  finishedAt?: Prisma.SortOrder
}

export type GameSumOrderByAggregateInput = {
  maxPlayers?: Prisma.SortOrder
}

export type GameScalarRelationFilter = {
  is?: Prisma.GameWhereInput
  isNot?: Prisma.GameWhereInput
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type GameCreateNestedOneWithoutPlayersInput = {
  create?: Prisma.XOR<Prisma.GameCreateWithoutPlayersInput, Prisma.GameUncheckedCreateWithoutPlayersInput>
  connectOrCreate?: Prisma.GameCreateOrConnectWithoutPlayersInput
  connect?: Prisma.GameWhereUniqueInput
}

export type GameUpdateOneRequiredWithoutPlayersNestedInput = {
  create?: Prisma.XOR<Prisma.GameCreateWithoutPlayersInput, Prisma.GameUncheckedCreateWithoutPlayersInput>
  connectOrCreate?: Prisma.GameCreateOrConnectWithoutPlayersInput
  upsert?: Prisma.GameUpsertWithoutPlayersInput
  connect?: Prisma.GameWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GameUpdateToOneWithWhereWithoutPlayersInput, Prisma.GameUpdateWithoutPlayersInput>, Prisma.GameUncheckedUpdateWithoutPlayersInput>
}

export type GameCreateNestedOneWithoutMovesInput = {
  create?: Prisma.XOR<Prisma.GameCreateWithoutMovesInput, Prisma.GameUncheckedCreateWithoutMovesInput>
  connectOrCreate?: Prisma.GameCreateOrConnectWithoutMovesInput
  connect?: Prisma.GameWhereUniqueInput
}

export type GameUpdateOneRequiredWithoutMovesNestedInput = {
  create?: Prisma.XOR<Prisma.GameCreateWithoutMovesInput, Prisma.GameUncheckedCreateWithoutMovesInput>
  connectOrCreate?: Prisma.GameCreateOrConnectWithoutMovesInput
  upsert?: Prisma.GameUpsertWithoutMovesInput
  connect?: Prisma.GameWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GameUpdateToOneWithWhereWithoutMovesInput, Prisma.GameUpdateWithoutMovesInput>, Prisma.GameUncheckedUpdateWithoutMovesInput>
}

export type GameCreateNestedOneWithoutMessagesInput = {
  create?: Prisma.XOR<Prisma.GameCreateWithoutMessagesInput, Prisma.GameUncheckedCreateWithoutMessagesInput>
  connectOrCreate?: Prisma.GameCreateOrConnectWithoutMessagesInput
  connect?: Prisma.GameWhereUniqueInput
}

export type GameUpdateOneRequiredWithoutMessagesNestedInput = {
  create?: Prisma.XOR<Prisma.GameCreateWithoutMessagesInput, Prisma.GameUncheckedCreateWithoutMessagesInput>
  connectOrCreate?: Prisma.GameCreateOrConnectWithoutMessagesInput
  upsert?: Prisma.GameUpsertWithoutMessagesInput
  connect?: Prisma.GameWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.GameUpdateToOneWithWhereWithoutMessagesInput, Prisma.GameUpdateWithoutMessagesInput>, Prisma.GameUncheckedUpdateWithoutMessagesInput>
}

export type GameCreateWithoutPlayersInput = {
  id: string
  mode?: string
  status?: string
  maxPlayers?: number
  settings?: string
  createdAt?: Date | string
  finishedAt?: Date | string | null
  moves?: Prisma.MoveCreateNestedManyWithoutGameInput
  messages?: Prisma.ChatMessageCreateNestedManyWithoutGameInput
}

export type GameUncheckedCreateWithoutPlayersInput = {
  id: string
  mode?: string
  status?: string
  maxPlayers?: number
  settings?: string
  createdAt?: Date | string
  finishedAt?: Date | string | null
  moves?: Prisma.MoveUncheckedCreateNestedManyWithoutGameInput
  messages?: Prisma.ChatMessageUncheckedCreateNestedManyWithoutGameInput
}

export type GameCreateOrConnectWithoutPlayersInput = {
  where: Prisma.GameWhereUniqueInput
  create: Prisma.XOR<Prisma.GameCreateWithoutPlayersInput, Prisma.GameUncheckedCreateWithoutPlayersInput>
}

export type GameUpsertWithoutPlayersInput = {
  update: Prisma.XOR<Prisma.GameUpdateWithoutPlayersInput, Prisma.GameUncheckedUpdateWithoutPlayersInput>
  create: Prisma.XOR<Prisma.GameCreateWithoutPlayersInput, Prisma.GameUncheckedCreateWithoutPlayersInput>
  where?: Prisma.GameWhereInput
}

export type GameUpdateToOneWithWhereWithoutPlayersInput = {
  where?: Prisma.GameWhereInput
  data: Prisma.XOR<Prisma.GameUpdateWithoutPlayersInput, Prisma.GameUncheckedUpdateWithoutPlayersInput>
}

export type GameUpdateWithoutPlayersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  maxPlayers?: Prisma.IntFieldUpdateOperationsInput | number
  settings?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  moves?: Prisma.MoveUpdateManyWithoutGameNestedInput
  messages?: Prisma.ChatMessageUpdateManyWithoutGameNestedInput
}

export type GameUncheckedUpdateWithoutPlayersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  maxPlayers?: Prisma.IntFieldUpdateOperationsInput | number
  settings?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  moves?: Prisma.MoveUncheckedUpdateManyWithoutGameNestedInput
  messages?: Prisma.ChatMessageUncheckedUpdateManyWithoutGameNestedInput
}

export type GameCreateWithoutMovesInput = {
  id: string
  mode?: string
  status?: string
  maxPlayers?: number
  settings?: string
  createdAt?: Date | string
  finishedAt?: Date | string | null
  players?: Prisma.GamePlayerCreateNestedManyWithoutGameInput
  messages?: Prisma.ChatMessageCreateNestedManyWithoutGameInput
}

export type GameUncheckedCreateWithoutMovesInput = {
  id: string
  mode?: string
  status?: string
  maxPlayers?: number
  settings?: string
  createdAt?: Date | string
  finishedAt?: Date | string | null
  players?: Prisma.GamePlayerUncheckedCreateNestedManyWithoutGameInput
  messages?: Prisma.ChatMessageUncheckedCreateNestedManyWithoutGameInput
}

export type GameCreateOrConnectWithoutMovesInput = {
  where: Prisma.GameWhereUniqueInput
  create: Prisma.XOR<Prisma.GameCreateWithoutMovesInput, Prisma.GameUncheckedCreateWithoutMovesInput>
}

export type GameUpsertWithoutMovesInput = {
  update: Prisma.XOR<Prisma.GameUpdateWithoutMovesInput, Prisma.GameUncheckedUpdateWithoutMovesInput>
  create: Prisma.XOR<Prisma.GameCreateWithoutMovesInput, Prisma.GameUncheckedCreateWithoutMovesInput>
  where?: Prisma.GameWhereInput
}

export type GameUpdateToOneWithWhereWithoutMovesInput = {
  where?: Prisma.GameWhereInput
  data: Prisma.XOR<Prisma.GameUpdateWithoutMovesInput, Prisma.GameUncheckedUpdateWithoutMovesInput>
}

export type GameUpdateWithoutMovesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  maxPlayers?: Prisma.IntFieldUpdateOperationsInput | number
  settings?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  players?: Prisma.GamePlayerUpdateManyWithoutGameNestedInput
  messages?: Prisma.ChatMessageUpdateManyWithoutGameNestedInput
}

export type GameUncheckedUpdateWithoutMovesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  maxPlayers?: Prisma.IntFieldUpdateOperationsInput | number
  settings?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  players?: Prisma.GamePlayerUncheckedUpdateManyWithoutGameNestedInput
  messages?: Prisma.ChatMessageUncheckedUpdateManyWithoutGameNestedInput
}

export type GameCreateWithoutMessagesInput = {
  id: string
  mode?: string
  status?: string
  maxPlayers?: number
  settings?: string
  createdAt?: Date | string
  finishedAt?: Date | string | null
  players?: Prisma.GamePlayerCreateNestedManyWithoutGameInput
  moves?: Prisma.MoveCreateNestedManyWithoutGameInput
}

export type GameUncheckedCreateWithoutMessagesInput = {
  id: string
  mode?: string
  status?: string
  maxPlayers?: number
  settings?: string
  createdAt?: Date | string
  finishedAt?: Date | string | null
  players?: Prisma.GamePlayerUncheckedCreateNestedManyWithoutGameInput
  moves?: Prisma.MoveUncheckedCreateNestedManyWithoutGameInput
}

export type GameCreateOrConnectWithoutMessagesInput = {
  where: Prisma.GameWhereUniqueInput
  create: Prisma.XOR<Prisma.GameCreateWithoutMessagesInput, Prisma.GameUncheckedCreateWithoutMessagesInput>
}

export type GameUpsertWithoutMessagesInput = {
  update: Prisma.XOR<Prisma.GameUpdateWithoutMessagesInput, Prisma.GameUncheckedUpdateWithoutMessagesInput>
  create: Prisma.XOR<Prisma.GameCreateWithoutMessagesInput, Prisma.GameUncheckedCreateWithoutMessagesInput>
  where?: Prisma.GameWhereInput
}

export type GameUpdateToOneWithWhereWithoutMessagesInput = {
  where?: Prisma.GameWhereInput
  data: Prisma.XOR<Prisma.GameUpdateWithoutMessagesInput, Prisma.GameUncheckedUpdateWithoutMessagesInput>
}

export type GameUpdateWithoutMessagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  maxPlayers?: Prisma.IntFieldUpdateOperationsInput | number
  settings?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  players?: Prisma.GamePlayerUpdateManyWithoutGameNestedInput
  moves?: Prisma.MoveUpdateManyWithoutGameNestedInput
}

export type GameUncheckedUpdateWithoutMessagesInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  mode?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  maxPlayers?: Prisma.IntFieldUpdateOperationsInput | number
  settings?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  finishedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  players?: Prisma.GamePlayerUncheckedUpdateManyWithoutGameNestedInput
  moves?: Prisma.MoveUncheckedUpdateManyWithoutGameNestedInput
}


/**
 * Count Type GameCountOutputType
 */

export type GameCountOutputType = {
  players: number
  moves: number
  messages: number
}

export type GameCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  players?: boolean | GameCountOutputTypeCountPlayersArgs
  moves?: boolean | GameCountOutputTypeCountMovesArgs
  messages?: boolean | GameCountOutputTypeCountMessagesArgs
}

/**
 * GameCountOutputType without action
 */
export type GameCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GameCountOutputType
   */
  select?: Prisma.GameCountOutputTypeSelect<ExtArgs> | null
}

/**
 * GameCountOutputType without action
 */
export type GameCountOutputTypeCountPlayersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.GamePlayerWhereInput
}

/**
 * GameCountOutputType without action
 */
export type GameCountOutputTypeCountMovesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MoveWhereInput
}

/**
 * GameCountOutputType without action
 */
export type GameCountOutputTypeCountMessagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ChatMessageWhereInput
}


export type GameSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mode?: boolean
  status?: boolean
  maxPlayers?: boolean
  settings?: boolean
  createdAt?: boolean
  finishedAt?: boolean
  players?: boolean | Prisma.Game$playersArgs<ExtArgs>
  moves?: boolean | Prisma.Game$movesArgs<ExtArgs>
  messages?: boolean | Prisma.Game$messagesArgs<ExtArgs>
  _count?: boolean | Prisma.GameCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["game"]>

export type GameSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mode?: boolean
  status?: boolean
  maxPlayers?: boolean
  settings?: boolean
  createdAt?: boolean
  finishedAt?: boolean
}, ExtArgs["result"]["game"]>

export type GameSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  mode?: boolean
  status?: boolean
  maxPlayers?: boolean
  settings?: boolean
  createdAt?: boolean
  finishedAt?: boolean
}, ExtArgs["result"]["game"]>

export type GameSelectScalar = {
  id?: boolean
  mode?: boolean
  status?: boolean
  maxPlayers?: boolean
  settings?: boolean
  createdAt?: boolean
  finishedAt?: boolean
}

export type GameOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "mode" | "status" | "maxPlayers" | "settings" | "createdAt" | "finishedAt", ExtArgs["result"]["game"]>
export type GameInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  players?: boolean | Prisma.Game$playersArgs<ExtArgs>
  moves?: boolean | Prisma.Game$movesArgs<ExtArgs>
  messages?: boolean | Prisma.Game$messagesArgs<ExtArgs>
  _count?: boolean | Prisma.GameCountOutputTypeDefaultArgs<ExtArgs>
}
export type GameIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}
export type GameIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $GamePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Game"
  objects: {
    players: Prisma.$GamePlayerPayload<ExtArgs>[]
    moves: Prisma.$MovePayload<ExtArgs>[]
    messages: Prisma.$ChatMessagePayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    mode: string
    status: string
    maxPlayers: number
    settings: string
    createdAt: Date
    finishedAt: Date | null
  }, ExtArgs["result"]["game"]>
  composites: {}
}

export type GameGetPayload<S extends boolean | null | undefined | GameDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$GamePayload, S>

export type GameCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<GameFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: GameCountAggregateInputType | true
  }

export interface GameDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Game'], meta: { name: 'Game' } }
  /**
   * Find zero or one Game that matches the filter.
   * @param {GameFindUniqueArgs} args - Arguments to find a Game
   * @example
   * // Get one Game
   * const game = await prisma.game.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends GameFindUniqueArgs>(args: Prisma.SelectSubset<T, GameFindUniqueArgs<ExtArgs>>): Prisma.Prisma__GameClient<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Game that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {GameFindUniqueOrThrowArgs} args - Arguments to find a Game
   * @example
   * // Get one Game
   * const game = await prisma.game.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends GameFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, GameFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__GameClient<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Game that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GameFindFirstArgs} args - Arguments to find a Game
   * @example
   * // Get one Game
   * const game = await prisma.game.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends GameFindFirstArgs>(args?: Prisma.SelectSubset<T, GameFindFirstArgs<ExtArgs>>): Prisma.Prisma__GameClient<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Game that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GameFindFirstOrThrowArgs} args - Arguments to find a Game
   * @example
   * // Get one Game
   * const game = await prisma.game.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends GameFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, GameFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__GameClient<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Games that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GameFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Games
   * const games = await prisma.game.findMany()
   * 
   * // Get first 10 Games
   * const games = await prisma.game.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const gameWithIdOnly = await prisma.game.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends GameFindManyArgs>(args?: Prisma.SelectSubset<T, GameFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Game.
   * @param {GameCreateArgs} args - Arguments to create a Game.
   * @example
   * // Create one Game
   * const Game = await prisma.game.create({
   *   data: {
   *     // ... data to create a Game
   *   }
   * })
   * 
   */
  create<T extends GameCreateArgs>(args: Prisma.SelectSubset<T, GameCreateArgs<ExtArgs>>): Prisma.Prisma__GameClient<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Games.
   * @param {GameCreateManyArgs} args - Arguments to create many Games.
   * @example
   * // Create many Games
   * const game = await prisma.game.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends GameCreateManyArgs>(args?: Prisma.SelectSubset<T, GameCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Games and returns the data saved in the database.
   * @param {GameCreateManyAndReturnArgs} args - Arguments to create many Games.
   * @example
   * // Create many Games
   * const game = await prisma.game.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Games and only return the `id`
   * const gameWithIdOnly = await prisma.game.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends GameCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, GameCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Game.
   * @param {GameDeleteArgs} args - Arguments to delete one Game.
   * @example
   * // Delete one Game
   * const Game = await prisma.game.delete({
   *   where: {
   *     // ... filter to delete one Game
   *   }
   * })
   * 
   */
  delete<T extends GameDeleteArgs>(args: Prisma.SelectSubset<T, GameDeleteArgs<ExtArgs>>): Prisma.Prisma__GameClient<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Game.
   * @param {GameUpdateArgs} args - Arguments to update one Game.
   * @example
   * // Update one Game
   * const game = await prisma.game.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends GameUpdateArgs>(args: Prisma.SelectSubset<T, GameUpdateArgs<ExtArgs>>): Prisma.Prisma__GameClient<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Games.
   * @param {GameDeleteManyArgs} args - Arguments to filter Games to delete.
   * @example
   * // Delete a few Games
   * const { count } = await prisma.game.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends GameDeleteManyArgs>(args?: Prisma.SelectSubset<T, GameDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Games.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GameUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Games
   * const game = await prisma.game.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends GameUpdateManyArgs>(args: Prisma.SelectSubset<T, GameUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Games and returns the data updated in the database.
   * @param {GameUpdateManyAndReturnArgs} args - Arguments to update many Games.
   * @example
   * // Update many Games
   * const game = await prisma.game.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Games and only return the `id`
   * const gameWithIdOnly = await prisma.game.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends GameUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, GameUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Game.
   * @param {GameUpsertArgs} args - Arguments to update or create a Game.
   * @example
   * // Update or create a Game
   * const game = await prisma.game.upsert({
   *   create: {
   *     // ... data to create a Game
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Game we want to update
   *   }
   * })
   */
  upsert<T extends GameUpsertArgs>(args: Prisma.SelectSubset<T, GameUpsertArgs<ExtArgs>>): Prisma.Prisma__GameClient<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Games.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GameCountArgs} args - Arguments to filter Games to count.
   * @example
   * // Count the number of Games
   * const count = await prisma.game.count({
   *   where: {
   *     // ... the filter for the Games we want to count
   *   }
   * })
  **/
  count<T extends GameCountArgs>(
    args?: Prisma.Subset<T, GameCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], GameCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Game.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GameAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends GameAggregateArgs>(args: Prisma.Subset<T, GameAggregateArgs>): Prisma.PrismaPromise<GetGameAggregateType<T>>

  /**
   * Group by Game.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {GameGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends GameGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: GameGroupByArgs['orderBy'] }
      : { orderBy?: GameGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, GameGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetGameGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Game model
 */
readonly fields: GameFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Game.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__GameClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  players<T extends Prisma.Game$playersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Game$playersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$GamePlayerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  moves<T extends Prisma.Game$movesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Game$movesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MovePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  messages<T extends Prisma.Game$messagesArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Game$messagesArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ChatMessagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Game model
 */
export interface GameFieldRefs {
  readonly id: Prisma.FieldRef<"Game", 'String'>
  readonly mode: Prisma.FieldRef<"Game", 'String'>
  readonly status: Prisma.FieldRef<"Game", 'String'>
  readonly maxPlayers: Prisma.FieldRef<"Game", 'Int'>
  readonly settings: Prisma.FieldRef<"Game", 'String'>
  readonly createdAt: Prisma.FieldRef<"Game", 'DateTime'>
  readonly finishedAt: Prisma.FieldRef<"Game", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Game findUnique
 */
export type GameFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Game
   */
  select?: Prisma.GameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Game
   */
  omit?: Prisma.GameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameInclude<ExtArgs> | null
  /**
   * Filter, which Game to fetch.
   */
  where: Prisma.GameWhereUniqueInput
}

/**
 * Game findUniqueOrThrow
 */
export type GameFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Game
   */
  select?: Prisma.GameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Game
   */
  omit?: Prisma.GameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameInclude<ExtArgs> | null
  /**
   * Filter, which Game to fetch.
   */
  where: Prisma.GameWhereUniqueInput
}

/**
 * Game findFirst
 */
export type GameFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Game
   */
  select?: Prisma.GameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Game
   */
  omit?: Prisma.GameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameInclude<ExtArgs> | null
  /**
   * Filter, which Game to fetch.
   */
  where?: Prisma.GameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Games to fetch.
   */
  orderBy?: Prisma.GameOrderByWithRelationInput | Prisma.GameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Games.
   */
  cursor?: Prisma.GameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Games from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Games.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Games.
   */
  distinct?: Prisma.GameScalarFieldEnum | Prisma.GameScalarFieldEnum[]
}

/**
 * Game findFirstOrThrow
 */
export type GameFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Game
   */
  select?: Prisma.GameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Game
   */
  omit?: Prisma.GameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameInclude<ExtArgs> | null
  /**
   * Filter, which Game to fetch.
   */
  where?: Prisma.GameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Games to fetch.
   */
  orderBy?: Prisma.GameOrderByWithRelationInput | Prisma.GameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Games.
   */
  cursor?: Prisma.GameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Games from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Games.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Games.
   */
  distinct?: Prisma.GameScalarFieldEnum | Prisma.GameScalarFieldEnum[]
}

/**
 * Game findMany
 */
export type GameFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Game
   */
  select?: Prisma.GameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Game
   */
  omit?: Prisma.GameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameInclude<ExtArgs> | null
  /**
   * Filter, which Games to fetch.
   */
  where?: Prisma.GameWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Games to fetch.
   */
  orderBy?: Prisma.GameOrderByWithRelationInput | Prisma.GameOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Games.
   */
  cursor?: Prisma.GameWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Games from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Games.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Games.
   */
  distinct?: Prisma.GameScalarFieldEnum | Prisma.GameScalarFieldEnum[]
}

/**
 * Game create
 */
export type GameCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Game
   */
  select?: Prisma.GameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Game
   */
  omit?: Prisma.GameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameInclude<ExtArgs> | null
  /**
   * The data needed to create a Game.
   */
  data: Prisma.XOR<Prisma.GameCreateInput, Prisma.GameUncheckedCreateInput>
}

/**
 * Game createMany
 */
export type GameCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Games.
   */
  data: Prisma.GameCreateManyInput | Prisma.GameCreateManyInput[]
}

/**
 * Game createManyAndReturn
 */
export type GameCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Game
   */
  select?: Prisma.GameSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Game
   */
  omit?: Prisma.GameOmit<ExtArgs> | null
  /**
   * The data used to create many Games.
   */
  data: Prisma.GameCreateManyInput | Prisma.GameCreateManyInput[]
}

/**
 * Game update
 */
export type GameUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Game
   */
  select?: Prisma.GameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Game
   */
  omit?: Prisma.GameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameInclude<ExtArgs> | null
  /**
   * The data needed to update a Game.
   */
  data: Prisma.XOR<Prisma.GameUpdateInput, Prisma.GameUncheckedUpdateInput>
  /**
   * Choose, which Game to update.
   */
  where: Prisma.GameWhereUniqueInput
}

/**
 * Game updateMany
 */
export type GameUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Games.
   */
  data: Prisma.XOR<Prisma.GameUpdateManyMutationInput, Prisma.GameUncheckedUpdateManyInput>
  /**
   * Filter which Games to update
   */
  where?: Prisma.GameWhereInput
  /**
   * Limit how many Games to update.
   */
  limit?: number
}

/**
 * Game updateManyAndReturn
 */
export type GameUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Game
   */
  select?: Prisma.GameSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Game
   */
  omit?: Prisma.GameOmit<ExtArgs> | null
  /**
   * The data used to update Games.
   */
  data: Prisma.XOR<Prisma.GameUpdateManyMutationInput, Prisma.GameUncheckedUpdateManyInput>
  /**
   * Filter which Games to update
   */
  where?: Prisma.GameWhereInput
  /**
   * Limit how many Games to update.
   */
  limit?: number
}

/**
 * Game upsert
 */
export type GameUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Game
   */
  select?: Prisma.GameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Game
   */
  omit?: Prisma.GameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameInclude<ExtArgs> | null
  /**
   * The filter to search for the Game to update in case it exists.
   */
  where: Prisma.GameWhereUniqueInput
  /**
   * In case the Game found by the `where` argument doesn't exist, create a new Game with this data.
   */
  create: Prisma.XOR<Prisma.GameCreateInput, Prisma.GameUncheckedCreateInput>
  /**
   * In case the Game was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.GameUpdateInput, Prisma.GameUncheckedUpdateInput>
}

/**
 * Game delete
 */
export type GameDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Game
   */
  select?: Prisma.GameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Game
   */
  omit?: Prisma.GameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameInclude<ExtArgs> | null
  /**
   * Filter which Game to delete.
   */
  where: Prisma.GameWhereUniqueInput
}

/**
 * Game deleteMany
 */
export type GameDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Games to delete
   */
  where?: Prisma.GameWhereInput
  /**
   * Limit how many Games to delete.
   */
  limit?: number
}

/**
 * Game.players
 */
export type Game$playersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the GamePlayer
   */
  select?: Prisma.GamePlayerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the GamePlayer
   */
  omit?: Prisma.GamePlayerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GamePlayerInclude<ExtArgs> | null
  where?: Prisma.GamePlayerWhereInput
  orderBy?: Prisma.GamePlayerOrderByWithRelationInput | Prisma.GamePlayerOrderByWithRelationInput[]
  cursor?: Prisma.GamePlayerWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.GamePlayerScalarFieldEnum | Prisma.GamePlayerScalarFieldEnum[]
}

/**
 * Game.moves
 */
export type Game$movesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Move
   */
  select?: Prisma.MoveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Move
   */
  omit?: Prisma.MoveOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MoveInclude<ExtArgs> | null
  where?: Prisma.MoveWhereInput
  orderBy?: Prisma.MoveOrderByWithRelationInput | Prisma.MoveOrderByWithRelationInput[]
  cursor?: Prisma.MoveWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.MoveScalarFieldEnum | Prisma.MoveScalarFieldEnum[]
}

/**
 * Game.messages
 */
export type Game$messagesArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChatMessage
   */
  select?: Prisma.ChatMessageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChatMessage
   */
  omit?: Prisma.ChatMessageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChatMessageInclude<ExtArgs> | null
  where?: Prisma.ChatMessageWhereInput
  orderBy?: Prisma.ChatMessageOrderByWithRelationInput | Prisma.ChatMessageOrderByWithRelationInput[]
  cursor?: Prisma.ChatMessageWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.ChatMessageScalarFieldEnum | Prisma.ChatMessageScalarFieldEnum[]
}

/**
 * Game without action
 */
export type GameDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Game
   */
  select?: Prisma.GameSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Game
   */
  omit?: Prisma.GameOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.GameInclude<ExtArgs> | null
}
