
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Move` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/wasm-compiler-edge"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Move
 * 
 */
export type MoveModel = runtime.Types.Result.DefaultSelection<Prisma.$MovePayload>

export type AggregateMove = {
  _count: MoveCountAggregateOutputType | null
  _avg: MoveAvgAggregateOutputType | null
  _sum: MoveSumAggregateOutputType | null
  _min: MoveMinAggregateOutputType | null
  _max: MoveMaxAggregateOutputType | null
}

export type MoveAvgAggregateOutputType = {
  seat: number | null
  sequence: number | null
}

export type MoveSumAggregateOutputType = {
  seat: number | null
  sequence: number | null
}

export type MoveMinAggregateOutputType = {
  id: string | null
  gameId: string | null
  seat: number | null
  sequence: number | null
  moveType: string | null
  data: string | null
  createdAt: Date | null
}

export type MoveMaxAggregateOutputType = {
  id: string | null
  gameId: string | null
  seat: number | null
  sequence: number | null
  moveType: string | null
  data: string | null
  createdAt: Date | null
}

export type MoveCountAggregateOutputType = {
  id: number
  gameId: number
  seat: number
  sequence: number
  moveType: number
  data: number
  createdAt: number
  _all: number
}


export type MoveAvgAggregateInputType = {
  seat?: true
  sequence?: true
}

export type MoveSumAggregateInputType = {
  seat?: true
  sequence?: true
}

export type MoveMinAggregateInputType = {
  id?: true
  gameId?: true
  seat?: true
  sequence?: true
  moveType?: true
  data?: true
  createdAt?: true
}

export type MoveMaxAggregateInputType = {
  id?: true
  gameId?: true
  seat?: true
  sequence?: true
  moveType?: true
  data?: true
  createdAt?: true
}

export type MoveCountAggregateInputType = {
  id?: true
  gameId?: true
  seat?: true
  sequence?: true
  moveType?: true
  data?: true
  createdAt?: true
  _all?: true
}

export type MoveAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Move to aggregate.
   */
  where?: Prisma.MoveWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Moves to fetch.
   */
  orderBy?: Prisma.MoveOrderByWithRelationInput | Prisma.MoveOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MoveWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Moves from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Moves.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Moves
  **/
  _count?: true | MoveCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: MoveAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: MoveSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MoveMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MoveMaxAggregateInputType
}

export type GetMoveAggregateType<T extends MoveAggregateArgs> = {
      [P in keyof T & keyof AggregateMove]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMove[P]>
    : Prisma.GetScalarType<T[P], AggregateMove[P]>
}




export type MoveGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MoveWhereInput
  orderBy?: Prisma.MoveOrderByWithAggregationInput | Prisma.MoveOrderByWithAggregationInput[]
  by: Prisma.MoveScalarFieldEnum[] | Prisma.MoveScalarFieldEnum
  having?: Prisma.MoveScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MoveCountAggregateInputType | true
  _avg?: MoveAvgAggregateInputType
  _sum?: MoveSumAggregateInputType
  _min?: MoveMinAggregateInputType
  _max?: MoveMaxAggregateInputType
}

export type MoveGroupByOutputType = {
  id: string
  gameId: string
  seat: number
  sequence: number
  moveType: string
  data: string
  createdAt: Date
  _count: MoveCountAggregateOutputType | null
  _avg: MoveAvgAggregateOutputType | null
  _sum: MoveSumAggregateOutputType | null
  _min: MoveMinAggregateOutputType | null
  _max: MoveMaxAggregateOutputType | null
}

export type GetMoveGroupByPayload<T extends MoveGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MoveGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MoveGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MoveGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MoveGroupByOutputType[P]>
      }
    >
  >



export type MoveWhereInput = {
  AND?: Prisma.MoveWhereInput | Prisma.MoveWhereInput[]
  OR?: Prisma.MoveWhereInput[]
  NOT?: Prisma.MoveWhereInput | Prisma.MoveWhereInput[]
  id?: Prisma.StringFilter<"Move"> | string
  gameId?: Prisma.StringFilter<"Move"> | string
  seat?: Prisma.IntFilter<"Move"> | number
  sequence?: Prisma.IntFilter<"Move"> | number
  moveType?: Prisma.StringFilter<"Move"> | string
  data?: Prisma.StringFilter<"Move"> | string
  createdAt?: Prisma.DateTimeFilter<"Move"> | Date | string
  game?: Prisma.XOR<Prisma.GameScalarRelationFilter, Prisma.GameWhereInput>
}

export type MoveOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  seat?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  moveType?: Prisma.SortOrder
  data?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  game?: Prisma.GameOrderByWithRelationInput
}

export type MoveWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  gameId_sequence?: Prisma.MoveGameIdSequenceCompoundUniqueInput
  AND?: Prisma.MoveWhereInput | Prisma.MoveWhereInput[]
  OR?: Prisma.MoveWhereInput[]
  NOT?: Prisma.MoveWhereInput | Prisma.MoveWhereInput[]
  gameId?: Prisma.StringFilter<"Move"> | string
  seat?: Prisma.IntFilter<"Move"> | number
  sequence?: Prisma.IntFilter<"Move"> | number
  moveType?: Prisma.StringFilter<"Move"> | string
  data?: Prisma.StringFilter<"Move"> | string
  createdAt?: Prisma.DateTimeFilter<"Move"> | Date | string
  game?: Prisma.XOR<Prisma.GameScalarRelationFilter, Prisma.GameWhereInput>
}, "id" | "gameId_sequence">

export type MoveOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  seat?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  moveType?: Prisma.SortOrder
  data?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  _count?: Prisma.MoveCountOrderByAggregateInput
  _avg?: Prisma.MoveAvgOrderByAggregateInput
  _max?: Prisma.MoveMaxOrderByAggregateInput
  _min?: Prisma.MoveMinOrderByAggregateInput
  _sum?: Prisma.MoveSumOrderByAggregateInput
}

export type MoveScalarWhereWithAggregatesInput = {
  AND?: Prisma.MoveScalarWhereWithAggregatesInput | Prisma.MoveScalarWhereWithAggregatesInput[]
  OR?: Prisma.MoveScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MoveScalarWhereWithAggregatesInput | Prisma.MoveScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Move"> | string
  gameId?: Prisma.StringWithAggregatesFilter<"Move"> | string
  seat?: Prisma.IntWithAggregatesFilter<"Move"> | number
  sequence?: Prisma.IntWithAggregatesFilter<"Move"> | number
  moveType?: Prisma.StringWithAggregatesFilter<"Move"> | string
  data?: Prisma.StringWithAggregatesFilter<"Move"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Move"> | Date | string
}

export type MoveCreateInput = {
  id?: string
  seat: number
  sequence: number
  moveType: string
  data: string
  createdAt?: Date | string
  game: Prisma.GameCreateNestedOneWithoutMovesInput
}

export type MoveUncheckedCreateInput = {
  id?: string
  gameId: string
  seat: number
  sequence: number
  moveType: string
  data: string
  createdAt?: Date | string
}

export type MoveUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  moveType?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  game?: Prisma.GameUpdateOneRequiredWithoutMovesNestedInput
}

export type MoveUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameId?: Prisma.StringFieldUpdateOperationsInput | string
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  moveType?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MoveCreateManyInput = {
  id?: string
  gameId: string
  seat: number
  sequence: number
  moveType: string
  data: string
  createdAt?: Date | string
}

export type MoveUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  moveType?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MoveUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  gameId?: Prisma.StringFieldUpdateOperationsInput | string
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  moveType?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MoveListRelationFilter = {
  every?: Prisma.MoveWhereInput
  some?: Prisma.MoveWhereInput
  none?: Prisma.MoveWhereInput
}

export type MoveOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MoveGameIdSequenceCompoundUniqueInput = {
  gameId: string
  sequence: number
}

export type MoveCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  seat?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  moveType?: Prisma.SortOrder
  data?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MoveAvgOrderByAggregateInput = {
  seat?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
}

export type MoveMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  seat?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  moveType?: Prisma.SortOrder
  data?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MoveMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  gameId?: Prisma.SortOrder
  seat?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
  moveType?: Prisma.SortOrder
  data?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
}

export type MoveSumOrderByAggregateInput = {
  seat?: Prisma.SortOrder
  sequence?: Prisma.SortOrder
}

export type MoveCreateNestedManyWithoutGameInput = {
  create?: Prisma.XOR<Prisma.MoveCreateWithoutGameInput, Prisma.MoveUncheckedCreateWithoutGameInput> | Prisma.MoveCreateWithoutGameInput[] | Prisma.MoveUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.MoveCreateOrConnectWithoutGameInput | Prisma.MoveCreateOrConnectWithoutGameInput[]
  createMany?: Prisma.MoveCreateManyGameInputEnvelope
  connect?: Prisma.MoveWhereUniqueInput | Prisma.MoveWhereUniqueInput[]
}

export type MoveUncheckedCreateNestedManyWithoutGameInput = {
  create?: Prisma.XOR<Prisma.MoveCreateWithoutGameInput, Prisma.MoveUncheckedCreateWithoutGameInput> | Prisma.MoveCreateWithoutGameInput[] | Prisma.MoveUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.MoveCreateOrConnectWithoutGameInput | Prisma.MoveCreateOrConnectWithoutGameInput[]
  createMany?: Prisma.MoveCreateManyGameInputEnvelope
  connect?: Prisma.MoveWhereUniqueInput | Prisma.MoveWhereUniqueInput[]
}

export type MoveUpdateManyWithoutGameNestedInput = {
  create?: Prisma.XOR<Prisma.MoveCreateWithoutGameInput, Prisma.MoveUncheckedCreateWithoutGameInput> | Prisma.MoveCreateWithoutGameInput[] | Prisma.MoveUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.MoveCreateOrConnectWithoutGameInput | Prisma.MoveCreateOrConnectWithoutGameInput[]
  upsert?: Prisma.MoveUpsertWithWhereUniqueWithoutGameInput | Prisma.MoveUpsertWithWhereUniqueWithoutGameInput[]
  createMany?: Prisma.MoveCreateManyGameInputEnvelope
  set?: Prisma.MoveWhereUniqueInput | Prisma.MoveWhereUniqueInput[]
  disconnect?: Prisma.MoveWhereUniqueInput | Prisma.MoveWhereUniqueInput[]
  delete?: Prisma.MoveWhereUniqueInput | Prisma.MoveWhereUniqueInput[]
  connect?: Prisma.MoveWhereUniqueInput | Prisma.MoveWhereUniqueInput[]
  update?: Prisma.MoveUpdateWithWhereUniqueWithoutGameInput | Prisma.MoveUpdateWithWhereUniqueWithoutGameInput[]
  updateMany?: Prisma.MoveUpdateManyWithWhereWithoutGameInput | Prisma.MoveUpdateManyWithWhereWithoutGameInput[]
  deleteMany?: Prisma.MoveScalarWhereInput | Prisma.MoveScalarWhereInput[]
}

export type MoveUncheckedUpdateManyWithoutGameNestedInput = {
  create?: Prisma.XOR<Prisma.MoveCreateWithoutGameInput, Prisma.MoveUncheckedCreateWithoutGameInput> | Prisma.MoveCreateWithoutGameInput[] | Prisma.MoveUncheckedCreateWithoutGameInput[]
  connectOrCreate?: Prisma.MoveCreateOrConnectWithoutGameInput | Prisma.MoveCreateOrConnectWithoutGameInput[]
  upsert?: Prisma.MoveUpsertWithWhereUniqueWithoutGameInput | Prisma.MoveUpsertWithWhereUniqueWithoutGameInput[]
  createMany?: Prisma.MoveCreateManyGameInputEnvelope
  set?: Prisma.MoveWhereUniqueInput | Prisma.MoveWhereUniqueInput[]
  disconnect?: Prisma.MoveWhereUniqueInput | Prisma.MoveWhereUniqueInput[]
  delete?: Prisma.MoveWhereUniqueInput | Prisma.MoveWhereUniqueInput[]
  connect?: Prisma.MoveWhereUniqueInput | Prisma.MoveWhereUniqueInput[]
  update?: Prisma.MoveUpdateWithWhereUniqueWithoutGameInput | Prisma.MoveUpdateWithWhereUniqueWithoutGameInput[]
  updateMany?: Prisma.MoveUpdateManyWithWhereWithoutGameInput | Prisma.MoveUpdateManyWithWhereWithoutGameInput[]
  deleteMany?: Prisma.MoveScalarWhereInput | Prisma.MoveScalarWhereInput[]
}

export type MoveCreateWithoutGameInput = {
  id?: string
  seat: number
  sequence: number
  moveType: string
  data: string
  createdAt?: Date | string
}

export type MoveUncheckedCreateWithoutGameInput = {
  id?: string
  seat: number
  sequence: number
  moveType: string
  data: string
  createdAt?: Date | string
}

export type MoveCreateOrConnectWithoutGameInput = {
  where: Prisma.MoveWhereUniqueInput
  create: Prisma.XOR<Prisma.MoveCreateWithoutGameInput, Prisma.MoveUncheckedCreateWithoutGameInput>
}

export type MoveCreateManyGameInputEnvelope = {
  data: Prisma.MoveCreateManyGameInput | Prisma.MoveCreateManyGameInput[]
}

export type MoveUpsertWithWhereUniqueWithoutGameInput = {
  where: Prisma.MoveWhereUniqueInput
  update: Prisma.XOR<Prisma.MoveUpdateWithoutGameInput, Prisma.MoveUncheckedUpdateWithoutGameInput>
  create: Prisma.XOR<Prisma.MoveCreateWithoutGameInput, Prisma.MoveUncheckedCreateWithoutGameInput>
}

export type MoveUpdateWithWhereUniqueWithoutGameInput = {
  where: Prisma.MoveWhereUniqueInput
  data: Prisma.XOR<Prisma.MoveUpdateWithoutGameInput, Prisma.MoveUncheckedUpdateWithoutGameInput>
}

export type MoveUpdateManyWithWhereWithoutGameInput = {
  where: Prisma.MoveScalarWhereInput
  data: Prisma.XOR<Prisma.MoveUpdateManyMutationInput, Prisma.MoveUncheckedUpdateManyWithoutGameInput>
}

export type MoveScalarWhereInput = {
  AND?: Prisma.MoveScalarWhereInput | Prisma.MoveScalarWhereInput[]
  OR?: Prisma.MoveScalarWhereInput[]
  NOT?: Prisma.MoveScalarWhereInput | Prisma.MoveScalarWhereInput[]
  id?: Prisma.StringFilter<"Move"> | string
  gameId?: Prisma.StringFilter<"Move"> | string
  seat?: Prisma.IntFilter<"Move"> | number
  sequence?: Prisma.IntFilter<"Move"> | number
  moveType?: Prisma.StringFilter<"Move"> | string
  data?: Prisma.StringFilter<"Move"> | string
  createdAt?: Prisma.DateTimeFilter<"Move"> | Date | string
}

export type MoveCreateManyGameInput = {
  id?: string
  seat: number
  sequence: number
  moveType: string
  data: string
  createdAt?: Date | string
}

export type MoveUpdateWithoutGameInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  moveType?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MoveUncheckedUpdateWithoutGameInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  moveType?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MoveUncheckedUpdateManyWithoutGameInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  seat?: Prisma.IntFieldUpdateOperationsInput | number
  sequence?: Prisma.IntFieldUpdateOperationsInput | number
  moveType?: Prisma.StringFieldUpdateOperationsInput | string
  data?: Prisma.StringFieldUpdateOperationsInput | string
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MoveSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gameId?: boolean
  seat?: boolean
  sequence?: boolean
  moveType?: boolean
  data?: boolean
  createdAt?: boolean
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
}, ExtArgs["result"]["move"]>

export type MoveSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gameId?: boolean
  seat?: boolean
  sequence?: boolean
  moveType?: boolean
  data?: boolean
  createdAt?: boolean
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
}, ExtArgs["result"]["move"]>

export type MoveSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  gameId?: boolean
  seat?: boolean
  sequence?: boolean
  moveType?: boolean
  data?: boolean
  createdAt?: boolean
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
}, ExtArgs["result"]["move"]>

export type MoveSelectScalar = {
  id?: boolean
  gameId?: boolean
  seat?: boolean
  sequence?: boolean
  moveType?: boolean
  data?: boolean
  createdAt?: boolean
}

export type MoveOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "gameId" | "seat" | "sequence" | "moveType" | "data" | "createdAt", ExtArgs["result"]["move"]>
export type MoveInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
}
export type MoveIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
}
export type MoveIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  game?: boolean | Prisma.GameDefaultArgs<ExtArgs>
}

export type $MovePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Move"
  objects: {
    game: Prisma.$GamePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    gameId: string
    seat: number
    sequence: number
    moveType: string
    data: string
    createdAt: Date
  }, ExtArgs["result"]["move"]>
  composites: {}
}

export type MoveGetPayload<S extends boolean | null | undefined | MoveDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MovePayload, S>

export type MoveCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MoveFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: MoveCountAggregateInputType | true
  }

export interface MoveDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Move'], meta: { name: 'Move' } }
  /**
   * Find zero or one Move that matches the filter.
   * @param {MoveFindUniqueArgs} args - Arguments to find a Move
   * @example
   * // Get one Move
   * const move = await prisma.move.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MoveFindUniqueArgs>(args: Prisma.SelectSubset<T, MoveFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MoveClient<runtime.Types.Result.GetResult<Prisma.$MovePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Move that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MoveFindUniqueOrThrowArgs} args - Arguments to find a Move
   * @example
   * // Get one Move
   * const move = await prisma.move.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MoveFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MoveFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MoveClient<runtime.Types.Result.GetResult<Prisma.$MovePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Move that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MoveFindFirstArgs} args - Arguments to find a Move
   * @example
   * // Get one Move
   * const move = await prisma.move.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MoveFindFirstArgs>(args?: Prisma.SelectSubset<T, MoveFindFirstArgs<ExtArgs>>): Prisma.Prisma__MoveClient<runtime.Types.Result.GetResult<Prisma.$MovePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Move that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MoveFindFirstOrThrowArgs} args - Arguments to find a Move
   * @example
   * // Get one Move
   * const move = await prisma.move.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MoveFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MoveFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MoveClient<runtime.Types.Result.GetResult<Prisma.$MovePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Moves that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MoveFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Moves
   * const moves = await prisma.move.findMany()
   * 
   * // Get first 10 Moves
   * const moves = await prisma.move.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const moveWithIdOnly = await prisma.move.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MoveFindManyArgs>(args?: Prisma.SelectSubset<T, MoveFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MovePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Move.
   * @param {MoveCreateArgs} args - Arguments to create a Move.
   * @example
   * // Create one Move
   * const Move = await prisma.move.create({
   *   data: {
   *     // ... data to create a Move
   *   }
   * })
   * 
   */
  create<T extends MoveCreateArgs>(args: Prisma.SelectSubset<T, MoveCreateArgs<ExtArgs>>): Prisma.Prisma__MoveClient<runtime.Types.Result.GetResult<Prisma.$MovePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Moves.
   * @param {MoveCreateManyArgs} args - Arguments to create many Moves.
   * @example
   * // Create many Moves
   * const move = await prisma.move.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MoveCreateManyArgs>(args?: Prisma.SelectSubset<T, MoveCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Moves and returns the data saved in the database.
   * @param {MoveCreateManyAndReturnArgs} args - Arguments to create many Moves.
   * @example
   * // Create many Moves
   * const move = await prisma.move.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Moves and only return the `id`
   * const moveWithIdOnly = await prisma.move.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends MoveCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, MoveCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MovePayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Move.
   * @param {MoveDeleteArgs} args - Arguments to delete one Move.
   * @example
   * // Delete one Move
   * const Move = await prisma.move.delete({
   *   where: {
   *     // ... filter to delete one Move
   *   }
   * })
   * 
   */
  delete<T extends MoveDeleteArgs>(args: Prisma.SelectSubset<T, MoveDeleteArgs<ExtArgs>>): Prisma.Prisma__MoveClient<runtime.Types.Result.GetResult<Prisma.$MovePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Move.
   * @param {MoveUpdateArgs} args - Arguments to update one Move.
   * @example
   * // Update one Move
   * const move = await prisma.move.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MoveUpdateArgs>(args: Prisma.SelectSubset<T, MoveUpdateArgs<ExtArgs>>): Prisma.Prisma__MoveClient<runtime.Types.Result.GetResult<Prisma.$MovePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Moves.
   * @param {MoveDeleteManyArgs} args - Arguments to filter Moves to delete.
   * @example
   * // Delete a few Moves
   * const { count } = await prisma.move.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MoveDeleteManyArgs>(args?: Prisma.SelectSubset<T, MoveDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Moves.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MoveUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Moves
   * const move = await prisma.move.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MoveUpdateManyArgs>(args: Prisma.SelectSubset<T, MoveUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Moves and returns the data updated in the database.
   * @param {MoveUpdateManyAndReturnArgs} args - Arguments to update many Moves.
   * @example
   * // Update many Moves
   * const move = await prisma.move.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Moves and only return the `id`
   * const moveWithIdOnly = await prisma.move.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends MoveUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, MoveUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MovePayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Move.
   * @param {MoveUpsertArgs} args - Arguments to update or create a Move.
   * @example
   * // Update or create a Move
   * const move = await prisma.move.upsert({
   *   create: {
   *     // ... data to create a Move
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Move we want to update
   *   }
   * })
   */
  upsert<T extends MoveUpsertArgs>(args: Prisma.SelectSubset<T, MoveUpsertArgs<ExtArgs>>): Prisma.Prisma__MoveClient<runtime.Types.Result.GetResult<Prisma.$MovePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Moves.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MoveCountArgs} args - Arguments to filter Moves to count.
   * @example
   * // Count the number of Moves
   * const count = await prisma.move.count({
   *   where: {
   *     // ... the filter for the Moves we want to count
   *   }
   * })
  **/
  count<T extends MoveCountArgs>(
    args?: Prisma.Subset<T, MoveCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MoveCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Move.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MoveAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MoveAggregateArgs>(args: Prisma.Subset<T, MoveAggregateArgs>): Prisma.PrismaPromise<GetMoveAggregateType<T>>

  /**
   * Group by Move.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MoveGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MoveGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MoveGroupByArgs['orderBy'] }
      : { orderBy?: MoveGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MoveGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMoveGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Move model
 */
readonly fields: MoveFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Move.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MoveClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  game<T extends Prisma.GameDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.GameDefaultArgs<ExtArgs>>): Prisma.Prisma__GameClient<runtime.Types.Result.GetResult<Prisma.$GamePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Move model
 */
export interface MoveFieldRefs {
  readonly id: Prisma.FieldRef<"Move", 'String'>
  readonly gameId: Prisma.FieldRef<"Move", 'String'>
  readonly seat: Prisma.FieldRef<"Move", 'Int'>
  readonly sequence: Prisma.FieldRef<"Move", 'Int'>
  readonly moveType: Prisma.FieldRef<"Move", 'String'>
  readonly data: Prisma.FieldRef<"Move", 'String'>
  readonly createdAt: Prisma.FieldRef<"Move", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Move findUnique
 */
export type MoveFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Move
   */
  select?: Prisma.MoveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Move
   */
  omit?: Prisma.MoveOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MoveInclude<ExtArgs> | null
  /**
   * Filter, which Move to fetch.
   */
  where: Prisma.MoveWhereUniqueInput
}

/**
 * Move findUniqueOrThrow
 */
export type MoveFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Move
   */
  select?: Prisma.MoveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Move
   */
  omit?: Prisma.MoveOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MoveInclude<ExtArgs> | null
  /**
   * Filter, which Move to fetch.
   */
  where: Prisma.MoveWhereUniqueInput
}

/**
 * Move findFirst
 */
export type MoveFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Move
   */
  select?: Prisma.MoveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Move
   */
  omit?: Prisma.MoveOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MoveInclude<ExtArgs> | null
  /**
   * Filter, which Move to fetch.
   */
  where?: Prisma.MoveWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Moves to fetch.
   */
  orderBy?: Prisma.MoveOrderByWithRelationInput | Prisma.MoveOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Moves.
   */
  cursor?: Prisma.MoveWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Moves from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Moves.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Moves.
   */
  distinct?: Prisma.MoveScalarFieldEnum | Prisma.MoveScalarFieldEnum[]
}

/**
 * Move findFirstOrThrow
 */
export type MoveFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Move
   */
  select?: Prisma.MoveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Move
   */
  omit?: Prisma.MoveOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MoveInclude<ExtArgs> | null
  /**
   * Filter, which Move to fetch.
   */
  where?: Prisma.MoveWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Moves to fetch.
   */
  orderBy?: Prisma.MoveOrderByWithRelationInput | Prisma.MoveOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Moves.
   */
  cursor?: Prisma.MoveWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Moves from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Moves.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Moves.
   */
  distinct?: Prisma.MoveScalarFieldEnum | Prisma.MoveScalarFieldEnum[]
}

/**
 * Move findMany
 */
export type MoveFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Move
   */
  select?: Prisma.MoveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Move
   */
  omit?: Prisma.MoveOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MoveInclude<ExtArgs> | null
  /**
   * Filter, which Moves to fetch.
   */
  where?: Prisma.MoveWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Moves to fetch.
   */
  orderBy?: Prisma.MoveOrderByWithRelationInput | Prisma.MoveOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Moves.
   */
  cursor?: Prisma.MoveWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Moves from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Moves.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Moves.
   */
  distinct?: Prisma.MoveScalarFieldEnum | Prisma.MoveScalarFieldEnum[]
}

/**
 * Move create
 */
export type MoveCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Move
   */
  select?: Prisma.MoveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Move
   */
  omit?: Prisma.MoveOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MoveInclude<ExtArgs> | null
  /**
   * The data needed to create a Move.
   */
  data: Prisma.XOR<Prisma.MoveCreateInput, Prisma.MoveUncheckedCreateInput>
}

/**
 * Move createMany
 */
export type MoveCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Moves.
   */
  data: Prisma.MoveCreateManyInput | Prisma.MoveCreateManyInput[]
}

/**
 * Move createManyAndReturn
 */
export type MoveCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Move
   */
  select?: Prisma.MoveSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Move
   */
  omit?: Prisma.MoveOmit<ExtArgs> | null
  /**
   * The data used to create many Moves.
   */
  data: Prisma.MoveCreateManyInput | Prisma.MoveCreateManyInput[]
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MoveIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Move update
 */
export type MoveUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Move
   */
  select?: Prisma.MoveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Move
   */
  omit?: Prisma.MoveOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MoveInclude<ExtArgs> | null
  /**
   * The data needed to update a Move.
   */
  data: Prisma.XOR<Prisma.MoveUpdateInput, Prisma.MoveUncheckedUpdateInput>
  /**
   * Choose, which Move to update.
   */
  where: Prisma.MoveWhereUniqueInput
}

/**
 * Move updateMany
 */
export type MoveUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Moves.
   */
  data: Prisma.XOR<Prisma.MoveUpdateManyMutationInput, Prisma.MoveUncheckedUpdateManyInput>
  /**
   * Filter which Moves to update
   */
  where?: Prisma.MoveWhereInput
  /**
   * Limit how many Moves to update.
   */
  limit?: number
}

/**
 * Move updateManyAndReturn
 */
export type MoveUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Move
   */
  select?: Prisma.MoveSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Move
   */
  omit?: Prisma.MoveOmit<ExtArgs> | null
  /**
   * The data used to update Moves.
   */
  data: Prisma.XOR<Prisma.MoveUpdateManyMutationInput, Prisma.MoveUncheckedUpdateManyInput>
  /**
   * Filter which Moves to update
   */
  where?: Prisma.MoveWhereInput
  /**
   * Limit how many Moves to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MoveIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Move upsert
 */
export type MoveUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Move
   */
  select?: Prisma.MoveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Move
   */
  omit?: Prisma.MoveOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MoveInclude<ExtArgs> | null
  /**
   * The filter to search for the Move to update in case it exists.
   */
  where: Prisma.MoveWhereUniqueInput
  /**
   * In case the Move found by the `where` argument doesn't exist, create a new Move with this data.
   */
  create: Prisma.XOR<Prisma.MoveCreateInput, Prisma.MoveUncheckedCreateInput>
  /**
   * In case the Move was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MoveUpdateInput, Prisma.MoveUncheckedUpdateInput>
}

/**
 * Move delete
 */
export type MoveDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Move
   */
  select?: Prisma.MoveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Move
   */
  omit?: Prisma.MoveOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MoveInclude<ExtArgs> | null
  /**
   * Filter which Move to delete.
   */
  where: Prisma.MoveWhereUniqueInput
}

/**
 * Move deleteMany
 */
export type MoveDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Moves to delete
   */
  where?: Prisma.MoveWhereInput
  /**
   * Limit how many Moves to delete.
   */
  limit?: number
}

/**
 * Move without action
 */
export type MoveDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Move
   */
  select?: Prisma.MoveSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Move
   */
  omit?: Prisma.MoveOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MoveInclude<ExtArgs> | null
}
